### ISSUE TITLE
timezone-related functions

### ISSUE THREAD

**Issue by lulalachen** [cullophid/date-fp#37] opened 2016-06-13 08:56 UTC
Hello @cullophid 
There's no timezone-related functionalities
I can help with that :)

**Comment by lulalachen** [comment] 2016-06-15 02:10
Maybe I'll simply add `getTimezoneOffset` by using native Date API
What do you think about this 😄

**Comment by cullophid** [comment] 2016-06-15 09:45
Hi @lulalachen sorry I haven't replied earlier.
This is something we have talked about, and It would be a great addition to date-fp.
I would love it if you did a PR for this.
What specific functions do you have in mind?
I think something like `D.get('timezoneOffset', date)` would make sense.

**Comment by lulalachen** [comment] 2016-06-15 17:57
Hello@cullophid that's not a problem at all 😄 
Yeah I thought about extending native function like you suggested `D.get('timezoneOffset', date)`
Besides, in the `parse` functionalities, I would like to add  `Z` (timezone) token.
Maybe like this

```
const date = new Date('2015-01-02 03:04:05.123');
D.format('YYYY-MM-DD HH:mm:ss Z', date); // '2015-01-02 03:04:05 +0800'
```

But I'm not so sure about this part, I'd love to do the `getter` part first 😄

**Comment by lulalachen** [comment] 2016-06-15 18:08
Here's the PR, thanks for reviewing it 😄 
PR #40

**Comment by cullophid** [comment] 2016-06-17 09:50
@lulalachen PR Merged.
It would be great to get timezone support in format and parse as well.
If you want to do a PR for those it would be great, otherwise I will have a look at it at some point.

**Comment by lulalachen** [comment] 2016-06-19 17:01
I can work on format and parse as well!
But I'm currently on trip haha so I will do it after Wednesday 😄

**Comment by TheLudd** [comment] 2016-06-23 19:49
Just ran across the issue with formatting according to timezone. How would that work? 
If I have a certain date and I want to format it with hours and minutes according to my specific timezone, is there a way to specify that?

**Comment by lulalachen** [comment] 2016-06-24 07:16
Hello @TheLudd
Sorry that I might misunderstand your question
In my understanding, we cannot do that in native `Date` object, because it always returns locale timezone.
I think it would be something like the following

``` javascript
const date = new Date('2015-01-02 03:04:05.123');
D.format('YYYY-MM-DD HH:mm:ss zz', date); // '2015-01-02 03:04:05 +0800'
```

**Comment by TheLudd** [comment] 2016-06-24 08:38
To make it clear: `const d = new Date(0)` will give us January 1st 1970 at midnight UCT.
I live in Sweden which is one hour ahead, so at that instance in time the clocks showed `01:00`.

So is there no way to do something like this?

```
D.format('YYYY-MM-DD HH:mm:ss [my timezone option]', d); // '1970-01-01 01:00:00'
```

Since we control the output, it should certanly be possible. I am just not sure if there is any standard way to specify a format like that.

**Comment by lulalachen** [comment] 2016-06-24 09:00
In my limited knowledge, there's no standard way to do things like this
but it's an important feature for certain!

**Comment by cullophid** [comment] 2016-06-27 13:59
I think this is a general issue with Javascript Dates. They don't have great support for timezones.
One options could be to use UTC dates and then apply the timezone offset before calling format.
I my opinion (if I understand your question right) the issue is not with format, but with the way dates are stored `get('hour', new Date(0))` also returns 1. 

The main problem is that Javascript Dates does not support timezones. Javscript dates are stored in UTC. 
Moment and other libs get around this by creating new date Classes. I wanted to avoid that. 

One solution could be to provide localized versions of functions like `getWithOffset :: Int -> String ->Date -> Int` `get(1, 'hours', new Date(0)) // 1`

**Comment by cullophid** [comment] 2016-06-27 14:01
It should be simple to configure the functions to work on localTime: `const get = getWithOffset(1)`

**Comment by cullophid** [comment] 2016-06-28 13:16
See: https://github.com/cullophid/date-fp/issues/41

**Closed as completed** 2016-07-04 14:13 UTC
